name: work_time_tracker
description: An app for tracking work time and calculating earnings

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

# Version information
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.1
  fl_chart: ^0.63.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  table_calendar: ^3.0.9
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.1
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section:
  assets:
    - assets/images/
    - assets/animations/
  
  # Add localization support
  generate: true

# Flutter launcher icons configuration  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_foreground: "assets/images/app_logo_foreground.png"
  remove_alpha_ios: true
